# Generated by Django 4.2.3 on 2023-07-10 16:58

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('content', models.TextField()),
            ],
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
